<a href="https://colab.research.google.com/github/ANKITHDEEGOJU/AI-ML-IITH-Course-Work/blob/MASTER/Python_Linear_Algebra_Sheet_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello World')

Hello World


A basic print function.

In [ ]:
#Some important things
# != ->LOgical XOR Operation
z=22
print(z**22)#-->Power of function
q=z.__sizeof__()#Gives us size of variable.
print(q)

341427877364219557396646723584
28


A quick overview of some imp points and some of the containers-list,dict,set,tuple..

In [ ]:
a=[10,True,'a',"a",123,1.23]  #defining a list
b=(12,112,"Yo") #defining a tuple
c={"Hello",123} #defining a set
d={"Hello":123,2:"Hi",3:"Jump"} #defining a dictionary

combo=[a,b,c,d]

#To display type of each variable
for x in combo:
  print(type(x))


<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'dict'>


In [ ]:
#Iterating through each individual container

#List
for x in a:
  print(type(x))
  print(a.index(x))

#Tuple
for x in b:
  print(x)

#Set
for x in c:
  print(x)

#Dictionary
for x,y in d.items():
  y=d.get(x)
  print('This {} has value {} associated with it.'.format(x,y))

#checking
print("Hello" in c)

<class 'int'>
0
<class 'bool'>
1
<class 'str'>
2
<class 'str'>
2
<class 'int'>
4
<class 'float'>
5
12
112
Yo
123
Hello
This Hello has value 123 associated with it.
This 2 has value Hi associated with it.
This 3 has value Jump associated with it.
True


In [ ]:
#Modifying  containers

# #Set
# c.add('wellness')
# c.remove('Hello')
# for s in c:
#   print(s)

# #List and Tuple similar
# a.append(8)
# a.remove(10)
# for s in a:
#   print(s)

#Dictionary
d["Hi"]=123
d.update({12:"ABCD"})
del d[12]
d.pop('Hi')
print(d.keys())


dict_keys(['Hello', 2, 3])


In [ ]:
# Funtions in python
def square(x,cube="True"):
  if(cube==True):
    print(x ** 3)
  print(x ** 2)
square(10)
square(12,cube=True)

100
1728
144


Starting out with numpy arrays

In [ ]:
import numpy as np
#Creating a single dimension arrray-->Rank=1
h=np.array([1,2,3,4,5,"Hello","Hi"])
print(h,h.ndim,h.shape)


# Creating a two dimension arrray-->Rank=2
u=np.array([[12,32,43],[21,34,56]])
print(u,u.ndim,u.shape)


['1' '2' '3' '4' '5' 'Hello' 'Hi'] 1 (7,)
[[12 32 43]
 [21 34 56]] 2 (2, 3)


In [ ]:
from numpy.core.fromnumeric import ndim
#Creating arrays

a=np.zeros((2,3))
print(a)

b=np.ones((1,3))
print(b)

c=np.full((3,1),8)
print(c)

d=np.eye(4,4)
print(d)

e=np.random.random((2,3))
print(e)

l=np.array([a,b,c,d,e],dtype=object)
for x in l:
  print(x.ndim,x.dtype)



In [ ]:
# Indexing and Slicing
v=np.array([[2,32,4],[1,4,6]])

print(v[1,0],v[0,1],v[1,2])


# Slicing
print(v[0:2]) #-->accessing rows

print(v[1,0:3]) #Accessing columns


1 32 6
[[ 2 32  4]
 [ 1  4  6]]
[1 4 6]


In [ ]:
# INdexing Methods

o=np.array([[1,2,3],[4,3,6],[9,7,6]])

#normal Indexing
b=o[:,:] #-->Accessing all rows and columns
c=o[1:,:1] #-->Accessing specific rows and columns
print(c)
print(b)

#Boolean Array Indexing
mask=b>2
select=b[mask]
print(select) #--> Returns values corressponding to true
print(mask) #-->Returns boolean values

#Integer Array Indexing
indices=np.array([0,1]) #--> Accessing the dimension
select_1=b[indices]
new_b=b.flatten()
select_2=new_b[indices]#--> Accesses according to indices if its of single dimension
print(select_1)
print(select_2)

[[4]
 [9]]
[[1 2 3]
 [4 3 6]
 [9 7 6]]
[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[[1 2 3]
 [4 3 6]]
[1 2]


In [ ]:
height=[180,175,155]
import numpy as a
np_height=a.array(height)
print(type(np_height))

<class 'numpy.ndarray'>


Element wise Calculations

In [ ]:
m_np_height=np_height*2
print(m_np_height)

[360 350 310]


Subsetting

In [ ]:
a=[100,125,135,132,150,180]
import numpy as np
m_a=np.array(a)
print("The array is ",m_a)
print("The new array after subsetting is ",m_a[m_a>135])


The array is  [100 125 135 132 150 180]
The new array after subsetting is  [150 180]


Basic Operations on array -

In [ ]:
x=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
y=np.array([[7,8,9],[10,11,12]],dtype=np.int32)

#Addition
print(x+y)
print(np.add(x,y))

#Addition
print(x+y)
print(np.add(x,y))

#Subtraction
print(x-y)
print(np.subtract(x,y))

#Multiplication
print(x*y)
print(np.multiply(x,y))

#Division
print(x/y)
print(np.divide(x,y))

#Sum
print(np.sum(x)) #-->Sum of all elements
print(np.sum(x,axis=0)) #-->Sum of elements in each column
print(np.sum(x,axis=1)) #-->Sum of elements in each row

[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
21
[5 7 9]
[ 6 15]


Dot Product and Transpose of a matrix

In [ ]:
import numpy as np
i=np.array([[2,5],[3,4]])
j=np.array([[6,1],[3,2]])
# Dot product
print(i @ j)
print(i.dot(j))
print(np.dot(i,j))

[[27 12]
 [30 11]]
[[27 12]
 [30 11]]
[[27 12]
 [30 11]]


In [ ]:
# Transposing
print(j.T)
p=np.transpose(j)
print(p)


#MAtrix Multiplication -->Similar to dot product
z=np.matmul(i,j)
print(z)

#Outer product-->Multipling each vector u1 with all vectors of v i,e v1,v2,v3 individually
l=np.outer(i,j)
print(l)

#Matrix Determinant
det=np.linalg.det(i)
print(det)

#Matrix Inversion
inv=np.linalg.inv(i)
print(inv)


#Matrix power for square matrices
a_1=np.linalg.matrix_power(i,2)
print(a_1)

#MAtrix rank
a_2=np.linalg.matrix_rank(i)
print(a_2)

[[6 3]
 [1 2]]
[[6 3]
 [1 2]]
[[27 12]
 [30 11]]
[[12  2  6  4]
 [30  5 15 10]
 [18  3  9  6]
 [24  4 12  8]]
-7.000000000000001
[[ 1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00]]
[[19 30]
 [18 31]]
2


In [ ]:
# Eigen values and vecors
m,n=np.linalg.eig(j)
print("The eigen value is {}".format(m))
print("The eigen vectors are {}".format(n))
#ONly to generaate the Eigen Values
eig_val=np.linalg.eigvals(j)
print(eig_val)

#Trace of a Matrix
s=np.trace(j)
print(s)

#like the concept of length for vectors, the norm provides a quantitative measure of how "large" the matrix is within a given context.
d=np.linalg.norm(j)
print("The Frobenius Norm of above matrix is {}".format(d))

The eigen value is [6.64575131 1.35424869]
The eigen vectors are [[ 0.84007078 -0.21043072]
 [ 0.54247681  0.97760877]]
[6.64575131 1.35424869]
8
The Frobenius Norm of above matrix is 7.0710678118654755


Solving system of Equations

In [ ]:
y=np.array([[2,-1,1],[1,1,0],[3,-1,2]]) #Coefficent Matrix
r=np.array([3,-1,7])#Constant Matrix
res=np.linalg.solve(y,r)#Contains Unknowns
print(res)

[-1.00000000e+00 -6.66133815e-16  5.00000000e+00]


Broadcasting

In [ ]:
# Scalar Broadcasting
import numpy as np
f=np.array([12,13,14])
scalar=10
res=f+scalar # Imagine how scalar got associated with each element and resulted in a completely new array
print(res)

# Dimension Broadcasting
g=np.array([[12,13,1],[10,20,30]])
h=np.array([14,32,21])
rex=g+h # Imagine how vector got associated with each element in g and resulted in a completely new array
print(rex)

[22 23 24]
[[26 45 22]
 [24 52 51]]


Single Value Decomposition